### ISSUE TITLE
Unable to let it work with react

### ISSUE THREAD

**Issue by bartio** [ngokevin/aframe-firebase-component#16]
Hi,
when I want to use this component with meteorjs 1.3, npm and react, I get and error:

> modules.js?hash=caf05d5…:82702 Uncaught (in promise) TypeError: Cannot read property 'ref' of undefined(…)

caused by  
```
import React, { Component } from 'react';
require('aframe');
require('aframe-firebase-component');

export default class App extends Component {
  
  render() {
    return (
     <a-scene firebase="apiKey: XXXXXX;
    authDomain: XXXXXX;
    databaseURL: XXXXXX;
    storageBucket: XXXXXX">
      <a-entity firebase-broadcast="components: rotation"></a-entity>
/a-scene>
    );
  }
}
```

Problem is definitely caused by `      <a-entity firebase-broadcast="components: rotation"></a-entity>
`. In case I use just plain html version, it works fine. When I delete firebase broadcast- firebase-broadcast="components: rotation", it pass through too. But I need to use it with meteor. Can you help? Thanks

**Comment by ngokevin** [comment]
Try using https://github.com/ngokevin/aframe-react
