### ISSUE TITLE
Fix broadcasted entities sometimes not disappearing when the user exits

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/aframe-firebase-component#6]
If I am broadcasting an entity to all other clients, for example, an avatar, When the client leaves (e.g., closes the browser tab, or turns off the device), the broadcasted entity should be detached.

There is currently logic for this by listening to `beforeunload` and `pagehide` and then making a call to Firebase to remove the entry. I am finding in some cases, perhaps iOS Safari, this is not working.

**Comment by amberroy** [comment]
I was able to repro this on both Safari and Chrome on iOS.  if I navigate away from the page it works correctly, but not if I close the browser while the app is running.
