### ISSUE TITLE
support rooms/channels

### ISSUE THREAD

**Issue by ngokevin** [ngokevin/aframe-firebase-component#7]
Currently, there is a single object created in Firebase `entities`.

We want to support rooms/channels.

```html
<a-scene firebase-broadcast-component="channel: nyan-cat">
```

This should store the entities under a namespace in Firebase:

```js
{
  entities: {
    "default": <ENTITIES>
    "nyan-cat": <ENTITIES>
  }
}
```

If a channel is not specified, we set the channel to `default`.

Allow the channel to be read in from the URL as well ```mysite.com?aframe-firebase-channel=oahu```

**Comment by amberroy** [comment]
How about this instead:
```
{
    default: {
       "entities": <ENTITIES>
    }
    nyan-cat: {
      "entities" <ENTITIES>
   }
}
```
In case we want to add support for keeping track of other things besides entities, e.g. "number of clients connected" or other per-channel data.

**Comment by amberroy** [comment]
opps didn't mean to close this.
