### ISSUE TITLE
Cannot checkout gh-pages branch

### ISSUE THREAD

**Issue by amberroy** [ngokevin/aframe-firebase-component#9]
Getting error on checkout (from GitShell command line) of gh-pages branch on my fork of this repo.

$ git checkout origin/gh-pages
fatal: cannot create directory at 'node_modules/budo/node_modules/browserify/node_modules/crypto-browserify/node_modules/browserify-cipher/node_modules/browserify-des/node_modules/des.js/node_modules/minimalistic-assert': Filename too long

**Comment by amberroy** [comment]
Removing the node_modules directory should fix the above error, I think it was committed by mistake as we don't need it on the gh-pages branch and it's not there for other A-Frame components such as [aframe-audio-visualizer-components](https://github.com/ngokevin/aframe-audio-visualizer-components/tree/gh-pages)

**Comment by amberroy** [comment]
I removed the node_modules in my gh-pages branch, but can't make a pull request since I wasn't able to checkout your gh-pages branch and had to re-created it from master.  

@ngokevin if my branch looks good I can force push it to your gh-pages, or you can replicate the fix.
https://github.com/amberroy/aframe-firebase-component/tree/gh-pages

**Comment by ngokevin** [comment]
https://github.com/ngokevin/aframe-firebase-component/tree/gh-pages

**Comment by ngokevin** [comment]
Thanks for investigating.
